spring:
  h2:
    console:
      enabled: true
      path: '/console'
  datasource:
    driver-class-name: org.h2.Driver
    url: ${H2_DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update